#!/bin/bash

fe=$(pwd)
output=$fe/../zijin-fe-compiled

output_public=$output/public

cd $fe

git pull

test -d $fe/node_modules/fe-tree || npm install --registry=https://registry.npm.taobao.org

if [[ $1 == "fast" ]]; then
    /usr/local/node/bin/node --max-old-space-size=2500 build-x/index.js --release=0 --total=1 --sourceHashFile=$output/sourceHash.json --outputHashFile=$output/outputHash.json
else
    /usr/local/node/bin/node --max-old-space-size=2500 build-x/index.js --release=1 --total=1 --sourceHashFile=$output/sourceHash.json --outputHashFile=$output/outputHash.json
fi


test -d $output_public || mkdir -p $output_public

test -d $fe/output/asset && cp -r $fe/output/asset $output_public
test -d $fe/output/dep && cp -r $fe/output/dep $output_public
test -d $fe/output/view && cp -r $fe/output/view $output

