#!/bin/bash

 br=$1

 fe=.

 output_public=../m2-fe-compiled

 output_public_old=../m-fe-compiled

 cd $fe

 git pull
 npm install --registry=https://registry.npm.taobao.org

 rm -rf $fe/output

 chmod +x $fe/build.js

 node $fe/build.js -s beta

 test -L $output_public_old/view/v2 || ln -s $output_public/view/v2 $output_public_old/view/v2

 test -d $output_public || mkdir -p $output_public

 test -d $fe/output/view && cp -r $fe/output/view $output_public
 test -d $fe/output/public && cp -r $fe/output/public $output_public
